StorageBodySize=100
StorageMotorSize=100
StorageAccessorySize=100
StorageAutoSize=50
AccessorySuppliers=5
BodySuppliers=3
MotorSuppliers=4
Workers=10
Dealers=20
SupplierDelay=1000
DealerDelay=2000
LogSale=true